### ISSUE TITLE
Skybox modification

### ISSUE THREAD

**Issue by thb-p** [lunar-insight/lunar-resources-insight#6]
Change the default Skybox of the Cesium globe engine.

The size should be 2:1, after testing, it should be more than 6000 x 3000 px and converted [here](https://jaxry.github.io/panorama-to-cubemap/) for simplicity. For realism, the [NASA SVS](https://svs.gsfc.nasa.gov/4851) can be used with a good resolution (8k is fine).

**Comment by thb-p** [comment]
04ba35b

**Comment by Astrareach** [comment]
**Note when using panorama to cubemap tool (with 0 deg rotation)**

Per image rotation necessary:

px = x2
nx = x2
pz = x2 then rename to nz
py = none
ny = none
nz = x2 then rename to pz
